import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.*;
import javax.swing.event.TableModelEvent;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.mail.Multipart;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;
import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.mail.MessagingException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BAPS
 */
public class orderdashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(orderdashboard.class.getName());
    public final ExecutorService emailExecutor=Executors.newFixedThreadPool(5);
    
    /**
     * Creates new form orderdashboard
     */
    public orderdashboard() {
        initComponents();
        styleTable();
        addHoverEffect();
        showLiveDateTime();
        rbAll.setSelected(true);
        addData(false);
        addTableUpdateListener();
        loadRevenue();

        
    }
    private void showLiveDateTime() {
    new javax.swing.Timer(1000, e -> {
        java.text.SimpleDateFormat sdf =
            new java.text.SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        lblDateTime.setText(sdf.format(new java.util.Date()));
    }).start();
    }
    private void addTableUpdateListener() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addTableModelListener(e -> {
            if (e.getType() != TableModelEvent.UPDATE) return;

            int row = e.getFirstRow();
            int col = e.getColumn();

            Object newValue = model.getValueAt(row, col);
            int orderId = Integer.parseInt(model.getValueAt(row, 0).toString());

            String columnName = model.getColumnName(col);
            updateOrderDatabase(columnName, newValue, orderId);
        });
    }

    private void updateOrderDatabase(String column, Object value, int orderId) {

        String sql;

        switch (column) {
            case "MRP" -> sql = "UPDATE order_book SET mrp=? WHERE o_id=?";
            case "Discount" -> sql = "UPDATE order_book SET discount=? WHERE o_id=?";
            case "Net Amount" -> sql = "UPDATE t_ransaction SET net_amt=? WHERE orderid=?";
            case "Payment Mode" -> sql = "UPDATE t_ransaction SET payment_mode=? WHERE orderid=?";
            case "Transaction Date" -> sql = "UPDATE t_ransaction SET tdate=? WHERE orderid=?";
            default -> {
                return;
            }
        }

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/retailbilling",
                "root", "PFH#9kgrw");
             PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setObject(1, value);
            pst.setInt(2, orderId);
            pst.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFilter = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblDateTime = new javax.swing.JLabel();
        rbAll = new javax.swing.JRadioButton();
        rbToday = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTodayText = new javax.swing.JLabel();
        lblTodayRevenue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAllRevenue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Order");

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("ORDER DASHBOARD");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Order Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Order Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 102));
        jButton3.setText("Transaction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 102));
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item ID", " MRP", "Discount", "Net Amount", "Payment Mode", "Transaction Date"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        lblDateTime.setBackground(new java.awt.Color(204, 204, 255));
        lblDateTime.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        lblDateTime.setText("--/--/---- --:--:--");

        rbAll.setBackground(new java.awt.Color(204, 204, 255));
        bgFilter.add(rbAll);
        rbAll.setFont(new java.awt.Font("Rockwell Condensed", 3, 14)); // NOI18N
        rbAll.setForeground(new java.awt.Color(0, 0, 102));
        rbAll.setText("All");
        rbAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllActionPerformed(evt);
            }
        });

        rbToday.setBackground(new java.awt.Color(204, 204, 255));
        bgFilter.add(rbToday);
        rbToday.setFont(new java.awt.Font("Rockwell Condensed", 3, 14)); // NOI18N
        rbToday.setForeground(new java.awt.Color(0, 0, 102));
        rbToday.setText("Today");
        rbToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodayActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Send Mail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        lblTodayText.setBackground(new java.awt.Color(204, 204, 255));
        lblTodayText.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        lblTodayText.setForeground(new java.awt.Color(0, 0, 102));
        lblTodayText.setText("Today's Revenue:");

        lblTodayRevenue.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTodayRevenue.setForeground(new java.awt.Color(0, 0, 102));
        lblTodayRevenue.setText("₹ 0.00");

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("All-Time Revenue:");

        lblAllRevenue.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblAllRevenue.setForeground(new java.awt.Color(0, 0, 102));
        lblAllRevenue.setText("₹ 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTodayText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTodayRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTodayText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTodayRevenue)
                    .addComponent(lblAllRevenue))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(rbAll, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbToday, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(153, 153, 153))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAll)
                    .addComponent(rbToday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        order_book ob=new order_book();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        orderitem oi=new orderitem();
        oi.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Transaction t=new Transaction();
        t.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        user u=new user();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rbAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAllActionPerformed
        // TODO add your handling code here:
        addData(false);
        loadRevenue();
    }//GEN-LAST:event_rbAllActionPerformed

    private void rbTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodayActionPerformed
        // TODO add your handling code here:
        addData(true);
        loadRevenue();
    }//GEN-LAST:event_rbTodayActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this,"Please select one order first");
            return;
        }
        String orderId=jTable1.getValueAt(row,0).toString();
        String orderDate=jTable1.getValueAt(row,6).toString();
        String netAmount=jTable1.getValueAt(row,4).toString();
        String email = JOptionPane.showInputDialog(
            this,
            "Enter Customer Email ID:",
            "Send Order Mail",
            JOptionPane.QUESTION_MESSAGE
    );
    if (email == null || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email not entered!");
        return;
    }
    sendOrderMail(email,orderId,orderDate,netAmount);

        
    }//GEN-LAST:event_jButton5ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new orderdashboard().setVisible(true));
    }
    private String generateBillPDF(String orderId, String orderDate, String netAmount) {

    String filePath = "C:\\Users\\BAPS\\Desktop\\Bill_" + orderId + ".pdf";

    try {
        Document doc = new Document(PageSize.A4);
        PdfWriter.getInstance(doc, new FileOutputStream(filePath));
        doc.open();

        Paragraph title = new Paragraph("RETAIL SHOP BILL");
    title.setAlignment(Element.ALIGN_CENTER);
    doc.add(title);

        doc.add(new Paragraph("\nDate: " + orderDate));
        doc.add(new Paragraph("Order ID: " + orderId));
        doc.add(new Paragraph("\n"));

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        table.setSpacingAfter(10f);

        table.addCell(new PdfPCell(new Phrase("Description")));
        table.addCell(new PdfPCell(new Phrase("Details")));

    table.addCell("Order ID");
    table.addCell(orderId);

    table.addCell("Order Date");
    table.addCell(orderDate);

    table.addCell("Net Amount");
    table.addCell("₹ " + netAmount);

    doc.add(table);

    Paragraph thanks = new Paragraph(
                    "Thank you for shopping with us!\nVisit Again 😊");
                thanks.setAlignment(Element.ALIGN_CENTER);
                doc.add(thanks);

        doc.close();

    } catch (DocumentException | FileNotFoundException e) {
        JOptionPane.showMessageDialog(this, "PDF Error: " + e.getMessage());
    }

    return filePath;
}

    private void sendOrderMail(String toEmail, String orderId, String orderDate, String netAmount) {

    final String fromEmail = "palakmaithia@gmail.com";
    final String password = "fnhdojdwxzkbpvnf";

    // 🔹 Generate PDF
    String pdfPath = generateBillPDF(orderId, orderDate, netAmount);

    Properties props = new Properties();
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");

    Session session = Session.getInstance(props, new Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(fromEmail, password);
        }
    });
    emailExecutor.submit(()->{

    try {
        Message msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress(fromEmail));
        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
        msg.setSubject("Order Bill - Order ID " + orderId);

        // 🔹 Mail body
        MimeBodyPart textPart = new MimeBodyPart();
        String html =
            "<h2>Order Bill</h2>" +
            "<p>Please find attached your bill.</p>" +
            "<b>Order ID:</b> " + orderId + "<br>" +
            "<b>Order Date:</b> " + orderDate + "<br>" +
            "<b>Net Amount:</b> ₹" + netAmount;

        textPart.setContent(html, "text/html");

        // 🔹 PDF attachment
        MimeBodyPart pdfPart = new MimeBodyPart();
        pdfPart.attachFile(new File(pdfPath));

        Multipart multipart = new MimeMultipart();
        multipart.addBodyPart(textPart);
        multipart.addBodyPart(pdfPart);

        msg.setContent(multipart);

        Transport.send(msg);
        Thread.sleep(3000);
        JOptionPane.showMessageDialog(this, "Mail sent with PDF bill!");

    } catch (HeadlessException | IOException | InterruptedException | MessagingException e) {
        JOptionPane.showMessageDialog(this, "Mail Error: " + e.getMessage());
    }finally
    {
        emailExecutor.shutdown();
    }
    });
}


    private void addData(boolean todayOnly) {

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/retailbilling","root","PFH#9kgrw");
            String sql = "SELECT ob.o_id, oi.i_id, ob.mrp, ob.discount, " +
                         "t.net_amt, t.payment_mode, t.tdate " +
                         "FROM order_book ob " +
                         "JOIN order_item oi ON oi.order_id = ob.o_id " +
                         "JOIN t_ransaction t ON t.orderid = ob.o_id ";
            if (todayOnly){
                sql=sql+"WHERE DATE(t.tdate) = CURDATE()";
            }
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("o_id"),
                    rs.getInt("i_id"),
                    rs.getDouble("mrp"),
                    rs.getDouble("discount"),
                    rs.getDouble("net_amt"),
                    rs.getString("payment_mode"),
                    rs.getDate("tdate")
                });
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}
    private void loadRevenue() {

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/retailbilling",
            "root", "PFH#9kgrw")) {

        // ----- Today's Revenue -----
        String todaySql =
            "SELECT IFNULL(SUM(net_amt),0) FROM t_ransaction " +
            "WHERE DATE(tdate) = CURDATE()";

        PreparedStatement pst = con.prepareStatement(todaySql);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            lblTodayRevenue.setText("₹ " + rs.getDouble(1));
        }
        String allSql =
            "SELECT IFNULL(SUM(net_amt),0) FROM t_ransaction";

        pst = con.prepareStatement(allSql);
        rs = pst.executeQuery();
        if (rs.next()) {
            lblAllRevenue.setText("₹ " + rs.getDouble(1));
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    private void styleTable() {

        // Header Styling
        jTable1.getTableHeader().setFont(new Font("Georgia", Font.BOLD, 12));
        jTable1.getTableHeader().setBackground(new Color(204, 204, 255));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 102));

        // Table Cell Font
        jTable1.setFont(new Font("Rockwell", Font.PLAIN, 13));
        jTable1.setRowHeight(25);

        // Center align all columns
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(center);
        }
    }
    // ================= HOVER EFFECT =================
    private int hoverRow = -1;
    private int hoverCol = -1;

    private void addHoverEffect() {

        jTable1.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                hoverRow = jTable1.rowAtPoint(e.getPoint());
                hoverCol = jTable1.columnAtPoint(e.getPoint());
                jTable1.repaint();
            }
        });

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseExited(MouseEvent e) {
                hoverRow = -1;
                hoverCol = -1;
                jTable1.repaint();
            }
        });

        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                // Default styling
                c.setBackground(Color.WHITE);
                c.setForeground(new Color(0, 0, 102));
                c.setFont(new Font("Rockwell", Font.PLAIN, 11));

                // Hover Row Effect
                if (row == hoverRow) {
                    c.setBackground(new Color(230, 230, 250)); // light lavender
                    c.setFont(new Font("Rockwell", Font.BOLD, 12));
                }

                // Hover Column Effect
                if (column == hoverCol) {
                    c.setBackground(new Color(204, 229, 255)); // light blue
                    c.setFont(new Font("Rockwell", Font.BOLD, 12));
                }

                // Selected Row Effect (override hover)
                if (isSelected) {
                    c.setBackground(new Color(160, 200, 255));
                    c.setForeground(Color.BLACK);
                    c.setFont(new Font("Rockwell", Font.BOLD, 12));
                }

                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAllRevenue;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblTodayRevenue;
    private javax.swing.JLabel lblTodayText;
    private javax.swing.JRadioButton rbAll;
    private javax.swing.JRadioButton rbToday;
    // End of variables declaration//GEN-END:variables

    private static class rbAll {

        public rbAll() {
        }
    }
}
